In [4]:
#inspection an array 
import numpy as np
a = [30, 40, 20, 40, 30]
arr = np.array(a)
print(arr)
print(arr.shape)


[30 40 20 40 30]
(5,)


In [6]:
#all function 
a = [[30, 40, 40],[40, 30, 10]]
arr = np.array(a)
print(arr)
print(arr.shape)
print(len(arr))
print(np.size(arr))
print(type(arr))
print(arr.dtype)
print(arr.astype(float))
print(arr.astype(str))
print(arr.astype(int))


[[30 40 40]
 [40 30 10]]
(2, 3)
2
6
<class 'numpy.ndarray'>
int64
[[30. 40. 40.]
 [40. 30. 10.]]
[['30' '40' '40']
 ['40' '30' '10']]
[[30 40 40]
 [40 30 10]]


In [8]:
#addition
arr1 = np.array([30, 40, 50, 60, 10])
arr2 =  np.array([30, 20, 30, 40, 50])
print(arr1 + arr2) #operation
print(np.add(arr1,arr2)) #function



[ 60  60  80 100  60]
[ 60  60  80 100  60]


In [11]:
import numpy as np
#subtraction 
arr1 = np.array([[30, 40],[20, 10]])
arr2 = np.array([[30, 20],[10, 20]])
print(np.subtract(arr1,arr2)) #function 
print(arr1 - arr2) #operation

[[  0  20]
 [ 10 -10]]
[[  0  20]
 [ 10 -10]]


In [16]:
import numpy as np 
#multiplication
arr1 = np.array([[30, 40],[20, 10]])
arr2 = np.array([[30, 20],[10, 20]])
print(arr1*arr2)
print()
print("***according numpy function****",np.multiply(arr1,arr2)) 

[[900 800]
 [200 200]]

***according numpy function**** [[900 800]
 [200 200]]


In [17]:
import numpy as np
#division 
arr1 = np.array([[30, 20], [40, 30]])
arr2 = np.array([[10, 2], [8, 3]])
print(arr1/arr2)
print()
print("***according numpy fuction***",np.divide(arr1,arr2))


[[ 3. 10.]
 [ 5. 10.]]

***according numpy fuction*** [[ 3. 10.]
 [ 5. 10.]]


In [18]:
import numpy as np 
#power
arr1 = np.array([3, 4, 5, 6, 7])
arr2 = np.array([2])
print(arr1**arr2)
print()
print("***according power***", np.power(arr1,arr2))

[ 9 16 25 36 49]

***according power*** [ 9 16 25 36 49]


In [20]:
import numpy as np
#square root 
arr1 = np.array([27, 64, 8, 1])
print(np.sqrt(arr1))

[5.19615242 8.         2.82842712 1.        ]


In [22]:
import numpy as np
#square root 
arr1 = np.array([9,16,4,1])
print(np.sqrt(arr1))

[3. 4. 2. 1.]


In [30]:
#combinating and spliting array.
# humare pass jab do array hote hai hum kese join kare sakte hai.
#ya fir humare pass single array unsko kese split kar sakte hai vo kese kare/
import numpy as np
#concatenate
arr1 = np.array([[30, 40, 50]])
arr2 = np.array([[5, 6, 7]])
print(np.concatenate([arr1,arr2]))
print()
#axis related x,y
print(np.concatenate([arr1,arr2],axis=0))  #horizontal its mean x axis
print()
print(np.concatenate([arr1,arr2],axis=1)) #vertical it's mean y axis (it is work 





[[30 40 50]
 [ 5  6  7]]

[[30 40 50  5  6  7]]


In [37]:
#split function
import numpy as np
a = np.array([20, 40, 50, 60,70])
print(np.array_split(a, 3)) #(a,3) mean a variable ko 3 portion mai split kar dega.


[array([20, 40]), array([50, 60]), array([70])]


In [40]:
import numpy as np
a = np.array([20,30,40,50,20])
b = np.array_split(a,3)
print(b)
print()
print(b[1])

[array([20, 30]), array([40, 50]), array([20])]

[40 50]


In [42]:
a = np.array([20,40,30,40,10,20])
b = np.array_split(a,4)
print(b)
print()
print(b[2])

[array([20, 40]), array([30, 40]), array([10]), array([20])]

[10]


In [44]:
a = np.array([20,40,50,60,70,10])
b = np.array_split(a,6)
print(b)
print()
print(b[3])

[array([20]), array([40]), array([50]), array([60]), array([70]), array([10])]

[60]


In [47]:
# 2d array
a = np.array([[20,30,40],[40,10,20]])
b = np.array_split(a,3)
print(b)


[array([[20, 30, 40]]), array([[40, 10, 20]]), array([], shape=(0, 3), dtype=int64)]


In [48]:
# adding and removing element in the array
#jese list le andar koi bhi value ko add karna hota hai.
#append
import numpy as np
a = np.array([20,30,40,50,60])
print(np.append(a, 90)) #(a,90) append ka use karke hum variable a me 90 ko add karwa denge 



[20 30 40 50 60 90]


In [49]:
#using append method to add 90 and 100 in 2D array.
a = np.array([[20,30],[60,80]])
print(np.append(a,[90,100])) 


[ 20  30  60  80  90 100]


In [50]:
#insert ---- ye tab use hota hai jaha par ek particular index me add karwa hai.
a = np.array([[50,60],[60,80]])
print(np.insert(a,1,[80,30]))

[50 80 30 60 60 80]


In [51]:
#insert 
a = np.array([[20,30],[10,50]])
print(np.insert(a,1,70))

[20 70 30 10 50]


In [55]:
#insert
a = np.array([[20,60],[40,90]])
print(np.insert(a,1,[50,30]))
print()
print(np.insert(a,1,[50,30], axis =1))
print()
print(np.insert(a,1,[50,30],axis = 0))


[20 50 30 60 40 90]

[[20 50 60]
 [40 30 90]]

[[20 60]
 [50 30]
 [40 90]]


In [57]:
# numpy-----------sort-----------filter---------------and-------------------search
# short --- accending order mai jamana
ar = np.array([7,8,9,4,12,9])
print(np.sort(ar))

[ 4  7  8  9  9 12]


In [59]:
# sort 2d 
ar1 = np.array([[7,8,4,12,9],[2,8,6,5,1]])
print(np.sort(ar1))

[[ 4  7  8  9 12]
 [ 1  2  5  6  8]]


In [60]:
#filter 
import numpy as np
ar = np.array([20,30,40,50])
fr = [True,False,True,False]
new = ar[fr]
print(new)



[20 40]


In [62]:
#filter
ar = np.array([20,30,40,50])
fr = [True,False,False,False]
new = ar[fr]
print(new)


[20]


In [64]:
#filter
ar =  np.array([2,3,4,5])
fa = ar % 2 == 0
new = ar[fa]
fr = ar % 2 == 1
new1 = ar[fr]
print(new)
print()
print(new1)

[2 4]

[3 5]
